
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/department-api
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    port: 5672
    username: vzrysyzb
    password: 5mbiRHNi_CXv4na6zFhmhEhzWz-MlDPD
    virtual-host: vzrysyzb
    ssl:
      enabled: false

  jpa:
    hibernate:
      #ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      
flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
